SIZE = WIDTH, HEIGHT = 20, 20
SCALING_FACTOR = SCALE_X, SCALE_Y = 20, 20
REAL_SIZE = REAL_WIDTH, REAL_HEIGHT = WIDTH * SCALE_X, HEIGHT * SCALE_Y
DIES_ON_BORDER = False
FOOD_COLLECTABLE = False
FOODS_AT_A_TIME = 1
DEBUG_MODE = True
FRAMERATE = 8

def end_game():
    exit(0)