SIZE = WIDTH, HEIGHT = 32, 32
SCALING_FACTOR = SCALE_X, SCALE_Y = 16, 16
REAL_SIZE = REAL_WIDTH, REAL_HEIGHT = WIDTH * SCALE_X, HEIGHT * SCALE_Y
DIES_ON_BORDER = False
FOOD_COLLECTABLE = False
FOODS_AT_A_TIME = 1
DEBUG_MODE = True

def end_game():
    exit(0)